# Generated by Django 2.1.2 on 2019-01-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20190120_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
