# Generated by Django 2.1.5 on 2019-01-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20190120_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponseMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chatbot.Message')),
                ('text', models.TextField()),
                ('question_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.QuestionMessage')),
            ],
            bases=('chatbot.message',),
        ),
    ]
