# Generated by Django 2.1.5 on 2019-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_questionresponsemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='fb_id',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
