# Generated by Django 2.1.5 on 2019-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_quizquestion_fb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_default_question',
            field=models.BooleanField(default=True),
        ),
    ]
